all:  clean clear compile run  

compile:
	@echo "Compiling......"
	@g++ -std=c++11 TET.cpp main.cpp -o test1
	
run:
	@echo "Running the test...."
	./test1
	
clear:
	@clear
clean:
	@rm -f *.o
	@rm -f *.out
